//
//  MovieDetailInteractor.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovieDetailInteractor: MovieDetailInteractorProtocol {

    weak var presenter: MovieDetailPresenterProtocol?
}
