//
//  MovieDetailRouter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class MovieDetailRouterFactory {
    func make(movie: MovieModel) -> UIViewController {
        let view = MovieDetailViewController(nibName: nil, bundle: Bundle(for: MovieDetailRouter.self))
        let interactor = MovieDetailInteractorImp()
        let router = MovieDetailRouter()
        let presenter = MovieDetailPresenterImp(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        view.movie = movie
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
}

final class MovieDetailRouter: MovieDetailWireframe {

    weak var viewController: UIViewController?

    static func createModule(movie: MovieModel) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        return MovieDetailRouterFactory().make(movie: movie)
    }
}
