//
//  MovieDetailViewController.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class MovieDetailViewController: UIViewController, MovieDetailView {

	var presenter: MovieDetailPresenter?
    var movie: MovieModel?

    @IBOutlet weak var image: UIImageView!
    @IBOutlet weak var lblTitle: UILabel!
    @IBOutlet weak var lblReleaseDate: UILabel!
    @IBOutlet weak var lblVotes: UILabel!
    @IBOutlet weak var lblOverview: UITextView!

    override func viewDidLoad() {
        super.viewDidLoad()
        configView()
    }

    func configView() {
        guard let movie = movie else {
            return
        }
        lblTitle.text = movie.movie.title
        lblReleaseDate.text = "Fecha de estreno: \(movie.movie.releaseDate ?? "NA")"
        lblVotes.text = "Votos: \(String(movie.movie.voteAverage ?? 0.0))"
        lblOverview.text = movie.movie.overview
        image.layer.cornerRadius = 10.0
        image.image = movie.movieBackdrop
    }

}
