//
//  MovieDetailProtocols.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol MovieDetailWireframe: AnyObject {

}
// MARK: Presenter -
protocol MovieDetailPresenter: AnyObject {

}

// MARK: Interactor -
protocol MovieDetailInteractor: AnyObject {

  var presenter: MovieDetailPresenter? { get set }
}

// MARK: View -
protocol MovieDetailView: AnyObject {

  var presenter: MovieDetailPresenter? { get set }
}
