//
//  MovieDetailPresenter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovieDetailPresenter: MovieDetailPresenterProtocol {

    weak private var view: MovieDetailViewProtocol?
    var interactor: MovieDetailInteractorProtocol?
    private let router: MovieDetailWireframeProtocol

    init(interface: MovieDetailViewProtocol, interactor: MovieDetailInteractorProtocol?, router: MovieDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
