//
//  MovieDetailProtocols.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol MovieDetailWireframeProtocol: AnyObject {

}
// MARK: Presenter -
protocol MovieDetailPresenterProtocol: AnyObject {

}

// MARK: Interactor -
protocol MovieDetailInteractorProtocol: AnyObject {

  var presenter: MovieDetailPresenterProtocol? { get set }
}

// MARK: View -
protocol MovieDetailViewProtocol: AnyObject {

  var presenter: MovieDetailPresenterProtocol? { get set }
}
