//
//  MovieDetailRouter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MovieDetailRouter: MovieDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(movie: MovieModel) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MovieDetailViewController(nibName: nil, bundle: Bundle(for: MovieDetailRouter.self))
        let interactor = MovieDetailInteractor()
        let router = MovieDetailRouter()
        let presenter = MovieDetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        view.movie = movie
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
