//
//  MovieDetailPresenter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class MovieDetailPresenterImp: MovieDetailPresenter {

    weak private var view: MovieDetailView?
    var interactor: MovieDetailInteractor?
    private let router: MovieDetailWireframe

    init(interface: MovieDetailView, interactor: MovieDetailInteractor?, router: MovieDetailWireframe) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
