//
//  SearchMovieRouter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchMovieRouter: SearchMovieWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let storyboard = UIStoryboard(name: "SearchMovie", bundle: Bundle(for: SearchMovieRouter.self))
        guard let view = storyboard.instantiateViewController(withIdentifier: "SearchMovie") as? SearchMovieViewController else {
            fatalError()
        }
//        let view = SearchMovieViewController(nibName: "SearchMovieViewController", bundle: Bundle(for: SearchMovieRouter.self))
        let interactor = SearchMovieInteractor()
        let router = SearchMovieRouter()
        let presenter = SearchMoviePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
