//
//  SearchMovieViewController.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchMovieViewController: UIViewController, SearchMovieViewProtocol {

	var presenter: SearchMoviePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
