//
//  SearchMoviePresenter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class SearchMoviePresenterImp: SearchMoviePresenter {
    weak private var view: SearchMovieView?
    var interactor: SearchMovieInteractor?
    private let router: SearchMovieWireframe

    init(interface: SearchMovieView, interactor: SearchMovieInteractor?, router: SearchMovieWireframe) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getMovies(endPoint: EndPoint, endPointResult: @escaping (MovieResponseResult?) -> Void) {
        interactor?.getMovies(endPoint: endPoint, endPointResult: endPointResult)
    }
}
