//
//  SearchMovieProtocols.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol SearchMovieWireframe: AnyObject { }

// MARK: Presenter -
protocol SearchMoviePresenter: AnyObject {
    func getMovies(endPoint: EndPoint, endPointResult: @escaping (MovieResponseResult?) -> Void)
}

// MARK: Interactor -
protocol SearchMovieInteractor: AnyObject {
    var presenter: SearchMoviePresenter? { get set }
    func getMovies(endPoint: EndPoint, endPointResult: @escaping (MovieResponseResult?) -> Void)
}

// MARK: View -
protocol SearchMovieView: AnyObject {
    var presenter: SearchMoviePresenter? { get set }
}
