//
//  SearchMovieRouter.swift
//  BAZProject
//
//  Created 1030364 on 17/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class SearchViewRouterFactory {
    func make() -> UIViewController {
        let storyboard = UIStoryboard(name: "SearchMovie", bundle: Bundle(for: SearchMovieRouter.self))
        guard let view = storyboard.instantiateViewController(withIdentifier: "SearchMovie") as? SearchMovieViewController else {
            fatalError()
        }
        let interactor = SearchMovieInteractorImp()
        let router = SearchMovieRouter()
        let presenter = SearchMoviePresenterImp(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
}

final class SearchMovieRouter: SearchMovieWireframe {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        return SearchViewRouterFactory().make()
    }
}
