//
//  MainMovieViewController.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainMovieViewController: UITabBarController, MainMovieViewProtocol {

	var presenter: MainMoviePresenterProtocol?

    private var mainMovieTabs: [MainMovieTab] = []

    override func viewDidLoad() {
        super.viewDidLoad()
        setTabs()
        configureSearchButton()
    }

    private func setTabs() {
        self.viewControllers = mainMovieTabs.map { $0.uiViewController }
        guard let viewControllers = self.viewControllers else {
            return
        }
        for (index, controller) in viewControllers.enumerated() {
            if index < mainMovieTabs.count {
                controller.tabBarItem.title = mainMovieTabs[index].tabBarTitle
                controller.tabBarItem.image = UIImage(systemName: mainMovieTabs[index].tabBarImages)
            }
        }
    }

    func configure(tabs: [MainMovieTab]) {
        mainMovieTabs = tabs
    }

    func configureSearchButton() {
        let image = UIImage(systemName: "magnifyingglass")
        let searchButton = UIBarButtonItem(image: image, style: .plain, target: self, action: #selector(openSearchView))
        self.navigationItem.rightBarButtonItem = searchButton
    }

    @objc func openSearchView() {
        let searchView = SearchMovieRouter.createModule()
        self.navigationController?.pushViewController(searchView, animated: true)
    }

}
