//
//  MainMovieProtocols.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol MainMovieWireframeProtocol: AnyObject {

}
// MARK: Presenter -
protocol MainMoviePresenterProtocol: AnyObject {

}

// MARK: Interactor -
protocol MainMovieInteractorProtocol: AnyObject {

  var presenter: MainMoviePresenterProtocol? { get set }
}

// MARK: View -
protocol MainMovieViewProtocol: AnyObject {

  var presenter: MainMoviePresenterProtocol? { get set }
}
