//
//  MainMovieViewController.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainMovieViewController: UIViewController, MainMovieViewProtocol {

	var presenter: MainMoviePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
