//
//  MainMovieViewController.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainMovieViewController: UITabBarController, MainMovieView {

	var presenter: MainMoviePresenter?

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.setTabs()
        configureSearchButton()
    }

    private func configureSearchButton() {
        let image = UIImage(systemName: "magnifyingglass")
        let searchButton = UIBarButtonItem(image: image, style: .plain, target: self, action: #selector(openSearchView))
        self.navigationItem.rightBarButtonItem = searchButton
    }

    @objc func openSearchView() {
        let searchView = SearchMovieRouter.createModule()
        self.navigationController?.pushViewController(searchView, animated: true)
    }

}
