//
//  MainMovieProtocols.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol MainMovieWireframeProtocol: AnyObject {}

// MARK: Presenter -
protocol MainMoviePresenter: AnyObject {
    func setTabs()
}

protocol MovieListPresenter: AnyObject {
    func getMoviesService(page: Int?, endPointResult: @escaping (MovieResponseResult?) -> Void)
}

// MARK: Interactor -
protocol MainMovieInteractor: AnyObject {
    var presenter: MovieListPresenter? { get set }
    func getMoviesService(page: Int?, endPointResult: @escaping (MovieResponseResult?) -> Void)
}

// MARK: View -
protocol MainMovieView: AnyObject {
    var presenter: MainMoviePresenter? { get set }
}

protocol MovieListView: AnyObject {
    var presenter: MovieListPresenter? { get set }
}
