//
//  MainMovieRouter.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainMovieRouter: MainMovieWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let storyboard = UIStoryboard(name: "MainMovieViewController", bundle: nil)
        guard let movieViewController = storyboard.instantiateViewController(withIdentifier: "MainMovieViewController") as? MainMovieViewController else {
            fatalError()
        }
        movieViewController.configure(tabs: makeMovieTabs())
        let interactor = MainMovieInteractor()
        let router = MainMovieRouter()
        let presenter = MainMoviePresenter(interface: movieViewController, interactor: interactor, router: router)

        movieViewController.presenter = presenter
        interactor.presenter = presenter
        router.viewController = movieViewController

        return movieViewController
    }

    static func makeMovieTabs() -> [MainMovieTab] {
        return [
            MainMovieTab(uiViewController: MovieListRouter.createModule(endPoint: TrendingEndPoint(page: 1)), tabBarImages: "chart.line.uptrend.xyaxis.circle.fill", tabBarTitle: "Trending"),
            MainMovieTab(uiViewController: MovieListRouter.createModule(endPoint: NowPlayingEndPoint()), tabBarImages: "play.circle", tabBarTitle: "Now Playing"),
            MainMovieTab(uiViewController: MovieListRouter.createModule(endPoint: PopularEndPoint()), tabBarImages: "theatermasks", tabBarTitle: "Popular"),
            MainMovieTab(uiViewController: MovieListRouter.createModule(endPoint: TopRatedEndPoint()), tabBarImages: "star.fill", tabBarTitle: "Top Rated"),
            MainMovieTab(uiViewController: MovieListRouter.createModule(endPoint: UpcomingEndPoint()), tabBarImages: "arrowshape.turn.up.forward.circle", tabBarTitle: "Upcoming")
        ]
    }

}
