//
//  MainMovieRouter.swift
//  BAZProject
//
//  Created 1030364 on 18/10/22.
//  Copyright © 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainMovieRouter: MainMovieWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MainMovieViewController(nibName: nil, bundle: Bundle(for: MainMovieRouter.self))
        let interactor = MainMovieInteractor()
        let router = MainMovieRouter()
        let presenter = MainMoviePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
